#4 Issue fix
laurentiustamate94/netstandard-storage pull request #5
Opened 2018-06-27 12:55 UTC by adambarath

https://github.com/laurentiustamate94/netstandard-storage/issues/4

2018-06-27 13:03 UTC, adambarath commented
@laurentiustamate94 , please review and merge my PR. And also please create a new nuget release.

2018-06-27 20:57 UTC, laurentiustamate94 requested changes
please do make the changes and after this I will merge gladly

2018-06-27 20:57 UTC, laurentiustamate94 commented on Plugin.NetStandardStorage.Abstractions/Interfaces/IFolder.cs
> +        void DeleteWithContent();
please change to `DeleteRecursively`

2018-06-27 20:57 UTC, laurentiustamate94 commented on Plugin.NetStandardStorage/Implementations/Folder.cs
>              return System.IO.File.Exists(path);
new line here, before the return. I want initialization to be separated vertically from other concepts, like return in this case

2018-06-27 20:57 UTC, laurentiustamate94 commented on Plugin.NetStandardStorage/Implementations/Folder.cs
> +                Directory.Delete(this.FullPath, true);
please specify what `true` means by specifying the `recursive` parameter name, like this: `Directory.Delete(this.FullPath, recursive: true);`

2018-06-28 07:26 UTC, laurentiustamate94 approved these changes

2018-06-28 07:26 UTC, merged